### ISSUE TITLE
Добавить отображение цвета автомобиля

### ISSUE THREAD

**Issue by my-test-frank** [my-test-frank/cars#1]
Приложение отображет список автомобилей.
Нужно сделать, чтобы напротив каждого элемента списка стоял произвольный (на усмотрение разработчика) цвет.

**Comment by my-test-alice** [comment]
Френк, а как можно определять цвет? Генератором случайных чисел?

**Comment by my-test-frank** [comment]
Нет, генератор это сложно, сделай пожалуйста фиксированный цвет.

**Comment by my-test-alice** [comment]
ОК, я берусь за эту задачу.

**Comment by my-test-alice** [comment]
Что значит "на усмотрение"? Генератор случайных чисел подойдет?

**Comment by my-test-frank** [comment]
Это слишком сложно. Можешь установить фиксированный цвет, любой?

**Comment by my-test-alice** [comment]
ОК, я берусь
